### ISSUE TITLE
Error: Cannot find module 'tslint/lib/runner'

### ISSUE THREAD

**Issue by waveywhite** [jrparish/tslint-webpack-plugin#6]
Hi,

I'm getting the error below, which I can't work out. As far as I can tell I have the correct dependencies and configuration.

```
module.js:529
    throw err;
    ^

Error: Cannot find module 'tslint/lib/runner'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/XYZ/angular/node_modules/tslint-webpack-plugin/src/linter.js:1:87)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

In package.json I have the following in devDependencies
```
    "tslint": "^3.15.1",
    "tslint-webpack-plugin": "^1.0.0",
```

webpack.common.js contains:

```
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./helpers');
var TSLintPlugin = require('tslint-webpack-plugin');

module.exports = {
	entry: {
		'polyfills': './src/polyfills.ts',
		'vendor': './src/vendor.ts',
		'app': './src/main.ts'
	},

	resolve: {
		extensions: ['.ts', '.js']
	},

	module: {
		rules: [
			{
				test: /\.ts$/,
				loaders: [
					{
						loader: 'awesome-typescript-loader',
						options: { configFileName: helpers.root('src', 'tsconfig.json') }
					} , 'angular2-template-loader'
				]
			},
			{
				test: /\.html$/,
				loader: 'html-loader',
				include: helpers.root(),
			},
			{
				test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
				use: [
					{
						loader: 'url-loader',
						options: {
							limit: 10000,
							mimetype: 'application/font-woff'
						}
					}
				]
			},
			{
				test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
				use: [
					{ loader: 'file-loader' }
				]
			},
			{
				test: /\.(png|jpe?g|gif|svg|ico)$/,
				include: helpers.root('src'),
				loader: 'file-loader?name=img/[name].[hash].[ext]'
			},
			{
				test: /\.css$/,
				exclude: helpers.root('src', 'app'),
				loader: ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader?sourceMap' })
			},
			{
				test: /\.css$/,
				include: helpers.root('src', 'app'),
				loader: 'raw-loader'
			},
			{
				test: /\.scss$/,
				exclude: /node_modules/,
				loaders: ['raw-loader', 'sass-loader']
			}
		]
	},

	plugins: [
		// Workaround for angular/angular#11580
		new webpack.ContextReplacementPlugin(
			// The (\\|\/) piece accounts for path separators in *nix and Windows
			/angular(\\|\/)core(\\|\/)@angular/,
			helpers.root('./src'), // location of your src
			{} // a map of your routes
		),

		new webpack.optimize.CommonsChunkPlugin({
			name: ['app', 'vendor', 'polyfills']
		}),

		new HtmlWebpackPlugin({
			template: 'src/index.html'
		}),

		new TSLintPlugin({
			files: ['./src/**/*.ts']
		})
	]
};
```

**Comment by jrparish** [comment]
Hi @waveywhite 

Are you able to upgrade to tslint 4 or higher? Currently the plugin doesn't support versions below that.

**Comment by waveywhite** [comment]
That solved it, thank you.
